apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-api-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  monocular.yaml: |-
    mongodb:
      url: {{ template "mongodb.fullname" . }}:27017
      database: {{ .Values.mongodb.mongodbDatabase }}
{{ toYaml .Values.api.config | indent 4 -}}
