apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-ui
      annotations:
        checksum/config: {{ print .Values.api.config | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ui.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
          - name: vhost
            mountPath: /bitnami/nginx/conf/vhosts
          - name: config
            mountPath: /app/assets/js
        resources:
{{ toYaml .Values.ui.resources | indent 12 }}
      volumes:
      - name: vhost
        configMap:
          name: {{ template "fullname" . }}-ui-vhost
      - name: config
        configMap:
          name: {{ template "fullname" . }}-ui-config
