apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.ui.service.annotations }}
  annotations:
{{ toYaml .Values.ui.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.externalPort }}
    targetPort: {{ .Values.ui.service.internalPort }}
    protocol: TCP
    name: {{ .Values.ui.service.name }}
  selector:
    app: {{ template "fullname" . }}-ui
