package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/helm/monocular/src/api/swagger/models"
)

/*GetChartVersionReadmeOK Readme.md file content

swagger:response getChartVersionReadmeOK
*/
type GetChartVersionReadmeOK struct {

	// In: body
	Payload *models.ResourceData `json:"body,omitempty"`
}

// NewGetChartVersionReadmeOK creates GetChartVersionReadmeOK with default headers values
func NewGetChartVersionReadmeOK() *GetChartVersionReadmeOK {
	return &GetChartVersionReadmeOK{}
}

// WithPayload adds the payload to the get chart version readme o k response
func (o *GetChartVersionReadmeOK) WithPayload(payload *models.ResourceData) *GetChartVersionReadmeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chart version readme o k response
func (o *GetChartVersionReadmeOK) SetPayload(payload *models.ResourceData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartVersionReadmeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetChartVersionReadmeDefault unexpected error

swagger:response getChartVersionReadmeDefault
*/
type GetChartVersionReadmeDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChartVersionReadmeDefault creates GetChartVersionReadmeDefault with default headers values
func NewGetChartVersionReadmeDefault(code int) *GetChartVersionReadmeDefault {
	if code <= 0 {
		code = 500
	}

	return &GetChartVersionReadmeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get chart version readme default response
func (o *GetChartVersionReadmeDefault) WithStatusCode(code int) *GetChartVersionReadmeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get chart version readme default response
func (o *GetChartVersionReadmeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get chart version readme default response
func (o *GetChartVersionReadmeDefault) WithPayload(payload *models.Error) *GetChartVersionReadmeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chart version readme default response
func (o *GetChartVersionReadmeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartVersionReadmeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
