package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kubernetes-helm/monocular/src/api/swagger/restapi/operations/charts"
	"github.com/kubernetes-helm/monocular/src/api/swagger/restapi/operations/releases"
	"github.com/kubernetes-helm/monocular/src/api/swagger/restapi/operations/repositories"
)

// NewMonocularAPI creates a new Monocular instance
func NewMonocularAPI(spec *loads.Document) *MonocularAPI {
	return &MonocularAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
	}
}

/*MonocularAPI the monocular API */
type MonocularAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ReleasesCreateReleaseHandler sets the operation handler for the create release operation
	ReleasesCreateReleaseHandler releases.CreateReleaseHandler
	// RepositoriesCreateRepoHandler sets the operation handler for the create repo operation
	RepositoriesCreateRepoHandler repositories.CreateRepoHandler
	// ReleasesDeleteReleaseHandler sets the operation handler for the delete release operation
	ReleasesDeleteReleaseHandler releases.DeleteReleaseHandler
	// RepositoriesDeleteRepoHandler sets the operation handler for the delete repo operation
	RepositoriesDeleteRepoHandler repositories.DeleteRepoHandler
	// ChartsGetAllChartsHandler sets the operation handler for the get all charts operation
	ChartsGetAllChartsHandler charts.GetAllChartsHandler
	// ReleasesGetAllReleasesHandler sets the operation handler for the get all releases operation
	ReleasesGetAllReleasesHandler releases.GetAllReleasesHandler
	// RepositoriesGetAllReposHandler sets the operation handler for the get all repos operation
	RepositoriesGetAllReposHandler repositories.GetAllReposHandler
	// ChartsGetChartHandler sets the operation handler for the get chart operation
	ChartsGetChartHandler charts.GetChartHandler
	// ChartsGetChartVersionHandler sets the operation handler for the get chart version operation
	ChartsGetChartVersionHandler charts.GetChartVersionHandler
	// ChartsGetChartVersionsHandler sets the operation handler for the get chart versions operation
	ChartsGetChartVersionsHandler charts.GetChartVersionsHandler
	// ChartsGetChartsInRepoHandler sets the operation handler for the get charts in repo operation
	ChartsGetChartsInRepoHandler charts.GetChartsInRepoHandler
	// ReleasesGetReleaseHandler sets the operation handler for the get release operation
	ReleasesGetReleaseHandler releases.GetReleaseHandler
	// RepositoriesGetRepoHandler sets the operation handler for the get repo operation
	RepositoriesGetRepoHandler repositories.GetRepoHandler
	// HealthzHandler sets the operation handler for the healthz operation
	HealthzHandler HealthzHandler
	// ChartsSearchChartsHandler sets the operation handler for the search charts operation
	ChartsSearchChartsHandler charts.SearchChartsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *MonocularAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MonocularAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MonocularAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MonocularAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MonocularAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MonocularAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MonocularAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MonocularAPI
func (o *MonocularAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ReleasesCreateReleaseHandler == nil {
		unregistered = append(unregistered, "releases.CreateReleaseHandler")
	}

	if o.RepositoriesCreateRepoHandler == nil {
		unregistered = append(unregistered, "repositories.CreateRepoHandler")
	}

	if o.ReleasesDeleteReleaseHandler == nil {
		unregistered = append(unregistered, "releases.DeleteReleaseHandler")
	}

	if o.RepositoriesDeleteRepoHandler == nil {
		unregistered = append(unregistered, "repositories.DeleteRepoHandler")
	}

	if o.ChartsGetAllChartsHandler == nil {
		unregistered = append(unregistered, "charts.GetAllChartsHandler")
	}

	if o.ReleasesGetAllReleasesHandler == nil {
		unregistered = append(unregistered, "releases.GetAllReleasesHandler")
	}

	if o.RepositoriesGetAllReposHandler == nil {
		unregistered = append(unregistered, "repositories.GetAllReposHandler")
	}

	if o.ChartsGetChartHandler == nil {
		unregistered = append(unregistered, "charts.GetChartHandler")
	}

	if o.ChartsGetChartVersionHandler == nil {
		unregistered = append(unregistered, "charts.GetChartVersionHandler")
	}

	if o.ChartsGetChartVersionsHandler == nil {
		unregistered = append(unregistered, "charts.GetChartVersionsHandler")
	}

	if o.ChartsGetChartsInRepoHandler == nil {
		unregistered = append(unregistered, "charts.GetChartsInRepoHandler")
	}

	if o.ReleasesGetReleaseHandler == nil {
		unregistered = append(unregistered, "releases.GetReleaseHandler")
	}

	if o.RepositoriesGetRepoHandler == nil {
		unregistered = append(unregistered, "repositories.GetRepoHandler")
	}

	if o.HealthzHandler == nil {
		unregistered = append(unregistered, "HealthzHandler")
	}

	if o.ChartsSearchChartsHandler == nil {
		unregistered = append(unregistered, "charts.SearchChartsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MonocularAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MonocularAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *MonocularAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *MonocularAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MonocularAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *MonocularAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/releases"] = releases.NewCreateRelease(o.context, o.ReleasesCreateReleaseHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/repos"] = repositories.NewCreateRepo(o.context, o.RepositoriesCreateRepoHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/releases/{releaseName}"] = releases.NewDeleteRelease(o.context, o.ReleasesDeleteReleaseHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/repos/{repoName}"] = repositories.NewDeleteRepo(o.context, o.RepositoriesDeleteRepoHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts"] = charts.NewGetAllCharts(o.context, o.ChartsGetAllChartsHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/releases"] = releases.NewGetAllReleases(o.context, o.ReleasesGetAllReleasesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/repos"] = repositories.NewGetAllRepos(o.context, o.RepositoriesGetAllReposHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts/{repo}/{chartName}"] = charts.NewGetChart(o.context, o.ChartsGetChartHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts/{repo}/{chartName}/versions/{version}"] = charts.NewGetChartVersion(o.context, o.ChartsGetChartVersionHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts/{repo}/{chartName}/versions"] = charts.NewGetChartVersions(o.context, o.ChartsGetChartVersionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts/{repo}"] = charts.NewGetChartsInRepo(o.context, o.ChartsGetChartsInRepoHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/releases/{releaseName}"] = releases.NewGetRelease(o.context, o.ReleasesGetReleaseHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/repos/{repoName}"] = repositories.NewGetRepo(o.context, o.RepositoriesGetRepoHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/healthz"] = NewHealthz(o.context, o.HealthzHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/charts/search"] = charts.NewSearchCharts(o.context, o.ChartsSearchChartsHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MonocularAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
