package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartLinks chart links

swagger:model chartLinks
*/
type ChartLinks struct {

	/* related

	Required: true
	Min Length: 1
	*/
	Related *string `json:"related"`
}

// Validate validates this chart links
func (m *ChartLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRelated(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartLinks) validateRelated(formats strfmt.Registry) error {

	if err := validate.Required("related", "body", m.Related); err != nil {
		return err
	}

	if err := validate.MinLength("related", "body", string(*m.Related), 1); err != nil {
		return err
	}

	return nil
}
