package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartLatestRelationships chart latest relationships

swagger:model chartLatestRelationships
*/
type ChartLatestRelationships struct {

	/* chart version latest

	Required: true
	*/
	ChartVersionLatest *ChartVersionRelationshipAttributes `json:"chartVersionLatest"`
}

// Validate validates this chart latest relationships
func (m *ChartLatestRelationships) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChartVersionLatest(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartLatestRelationships) validateChartVersionLatest(formats strfmt.Registry) error {

	if err := validate.Required("chartVersionLatest", "body", m.ChartVersionLatest); err != nil {
		return err
	}

	if m.ChartVersionLatest != nil {

		if err := m.ChartVersionLatest.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
