package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartVersionReadme chart version readme

swagger:model chartVersionReadme
*/
type ChartVersionReadme struct {

	/* content

	Required: true
	Min Length: 1
	*/
	Content *string `json:"content"`
}

// Validate validates this chart version readme
func (m *ChartVersionReadme) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartVersionReadme) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("content", "body", m.Content); err != nil {
		return err
	}

	if err := validate.MinLength("content", "body", string(*m.Content), 1); err != nil {
		return err
	}

	return nil
}
