package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartResourceLinks chart resource links

swagger:model chartResourceLinks
*/
type ChartResourceLinks struct {

	/* canonical

	Required: true
	Min Length: 1
	*/
	Canonical *string `json:"canonical"`
}

// Validate validates this chart resource links
func (m *ChartResourceLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCanonical(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartResourceLinks) validateCanonical(formats strfmt.Registry) error {

	if err := validate.Required("canonical", "body", m.Canonical); err != nil {
		return err
	}

	if err := validate.MinLength("canonical", "body", string(*m.Canonical), 1); err != nil {
		return err
	}

	return nil
}
