package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartRelationship chart relationship

swagger:model chartRelationship
*/
type ChartRelationship struct {

	/* chart

	Required: true
	*/
	Chart *ChartAsRelationship `json:"chart"`
}

// Validate validates this chart relationship
func (m *ChartRelationship) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartRelationship) validateChart(formats strfmt.Registry) error {

	if err := validate.Required("chart", "body", m.Chart); err != nil {
		return err
	}

	if m.Chart != nil {

		if err := m.Chart.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
