package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChartVersionRelationship chart version relationship

swagger:model chartVersionRelationship
*/
type ChartVersionRelationship struct {

	/* chart version

	Required: true
	*/
	ChartVersion *ChartVersionAsRelationship `json:"chartVersion"`
}

// Validate validates this chart version relationship
func (m *ChartVersionRelationship) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChartVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartVersionRelationship) validateChartVersion(formats strfmt.Registry) error {

	if err := validate.Required("chartVersion", "body", m.ChartVersion); err != nil {
		return err
	}

	if m.ChartVersion != nil {

		if err := m.ChartVersion.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
