package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*LatestChartVersionRelationship latest chart version relationship

swagger:model latestChartVersionRelationship
*/
type LatestChartVersionRelationship struct {

	/* latest chart version

	Required: true
	*/
	LatestChartVersion *ChartVersionAsRelationship `json:"latestChartVersion"`
}

// Validate validates this latest chart version relationship
func (m *LatestChartVersionRelationship) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatestChartVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LatestChartVersionRelationship) validateLatestChartVersion(formats strfmt.Registry) error {

	if err := validate.Required("latestChartVersion", "body", m.LatestChartVersion); err != nil {
		return err
	}

	if m.LatestChartVersion != nil {

		if err := m.LatestChartVersion.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
