package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ResourceLink resource link

swagger:model resourceLink
*/
type ResourceLink struct {

	/* self

	Required: true
	Min Length: 1
	*/
	Self *string `json:"self"`
}

// Validate validates this resource link
func (m *ResourceLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSelf(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceLink) validateSelf(formats strfmt.Registry) error {

	if err := validate.Required("self", "body", m.Self); err != nil {
		return err
	}

	if err := validate.MinLength("self", "body", string(*m.Self), 1); err != nil {
		return err
	}

	return nil
}
