codecov:
  branch: master
  bot: null
  ci: null
  strict_yaml_branch: null
  max_report_age: null
  notify:
    after_n_builds: null
    countdown: null
    require_ci_to_pass: yes
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"
        only_pulls: null
        message: null
        flags: null
        paths: null

    hipchat:
      default:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null
        flags: null
        paths: null

    gitter:
      default:
        url: null
        threshold: null
        branches: null
        message: null
        only_pulls: null
        flags: null
        paths: null

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null
        flags: null
        paths: null

    irc:
      default:
        server: null
        channel: null
        branches: null
        threshold: null
        message: null
        flags: null
        paths: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: null
        flags: null
        paths: null

    patch:
      default:
        target: auto
        branches: null
        set_pending: yes
        base: auto
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: null
        flags: null
        paths: null

    changes:
      default:
        branches: null
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: null
        flags: null
        paths: null
  flags:
    default:
      branches: null
      ignore: null

  fixes: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
  flags: null
  paths:
    - "src/api"
