apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-chartsvc
  labels:
    app: {{ template "fullname" . }}-chartsvc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.chartsvc.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-chartsvc
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-chartsvc
        release: {{ .Release.Name }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: chartsvc
        image: {{ template "monocular.image" .Values.chartsvc.image }}
        command:
        - /chartsvc
        args:
        {{- if and .Values.global.mongoUrl (not .Values.mongodb.enabled) }}
        - --mongo-url={{ .Values.global.mongoUrl }}
        {{- else }}
        - --mongo-user=root
        - --mongo-url={{ template "mongodb.fullname" . }}
        env:
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mongodb.fullname" . }}
              key: mongodb-root-password
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.chartsvc.service.port }}
        livenessProbe:
{{ toYaml .Values.chartsvc.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.chartsvc.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.chartsvc.resources | indent 12 }}
    {{- with .Values.chartsvc.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.chartsvc.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.chartsvc.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
