apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-prerender
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.prerender.service.type }}
  ports:
  - port: {{ .Values.prerender.service.externalPort }}
    {{if (and (eq .Values.prerender.service.type "NodePort") (not (empty .Values.prerender.service.nodePort)))}}
    nodePort: {{.Values.prerender.service.nodePort}}
    {{end}}
    targetPort: {{ .Values.prerender.service.internalPort }}
    protocol: TCP
    name: {{ .Values.prerender.service.name }}
  selector:
    app: {{ template "fullname" . }}-prerender
