apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-prerender
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.prerender.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-prerender
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-prerender
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "monocular.image" .Values.prerender.image }}
        imagePullPolicy: {{ .Values.prerender.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.prerender.service.internalPort }}
        env:
          - name: IN_MEMORY_CACHE
            value: {{ .Values.prerender.cacheEnabled | quote }}
        resources:
{{ toYaml .Values.prerender.resources | indent 12 }}
    {{- with .Values.prerender.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.prerender.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.prerender.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
