apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-ui-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  overrides.js: |-
    window.monocular = {
      overrides: {
        googleAnalyticsId: '{{.Values.ui.googleAnalyticsId}}',
        appName: '{{.Values.ui.appName}}',
        aboutUrl: '{{.Values.ui.aboutUrl}}',
        {{- if .Values.ui.backendHostname }}
        backendHostname: '{{ .Values.ui.backendHostname }}',
        {{- end }}
      }
    };
  repos.json: |-
    {"data": {{ toJson .Values.sync.repos }}}
