apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-ui
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ui-config.yaml") . | sha256sum }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "monocular.image" .Values.ui.image }}
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ui.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
          - name: vhost
            mountPath: /bitnami/nginx/conf/vhosts
          - name: config
            mountPath: /app/assets/js
        resources:
{{ toYaml .Values.ui.resources | indent 12 }}
      volumes:
      - name: vhost
        configMap:
          name: {{ template "fullname" . }}-ui-vhost
      - name: config
        configMap:
          name: {{ template "fullname" . }}-ui-config
    {{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
