{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}-ui
  ingress:
  - ports:
    - port: {{ .Values.ui.service.internalPort }}
      protocol: TCP
{{- end }}
