package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewCreateReleaseParams creates a new CreateReleaseParams object
// with the default values initialized.
func NewCreateReleaseParams() CreateReleaseParams {
	var ()
	return CreateReleaseParams{}
}

// CreateReleaseParams contains all the bound params for the create release operation
// typically these are obtained from a http.Request
//
// swagger:parameters createRelease
type CreateReleaseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Information related with the new Helm release.
	  In: body
	*/
	Data CreateReleaseBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateReleaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body CreateReleaseBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("data", "body", "", err))
		} else {

			if len(res) == 0 {
				o.Data = body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
