package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubernetes-helm/monocular/src/api/swagger/models"
)

/*DeleteReleaseOK release deleted

swagger:response deleteReleaseOK
*/
type DeleteReleaseOK struct {

	// In: body
	Payload *models.ResourceData `json:"body,omitempty"`
}

// NewDeleteReleaseOK creates DeleteReleaseOK with default headers values
func NewDeleteReleaseOK() *DeleteReleaseOK {
	return &DeleteReleaseOK{}
}

// WithPayload adds the payload to the delete release o k response
func (o *DeleteReleaseOK) WithPayload(payload *models.ResourceData) *DeleteReleaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release o k response
func (o *DeleteReleaseOK) SetPayload(payload *models.ResourceData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteReleaseDefault unexpected error

swagger:response deleteReleaseDefault
*/
type DeleteReleaseDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteReleaseDefault creates DeleteReleaseDefault with default headers values
func NewDeleteReleaseDefault(code int) *DeleteReleaseDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteReleaseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete release default response
func (o *DeleteReleaseDefault) WithStatusCode(code int) *DeleteReleaseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete release default response
func (o *DeleteReleaseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete release default response
func (o *DeleteReleaseDefault) WithPayload(payload *models.Error) *DeleteReleaseDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release default response
func (o *DeleteReleaseDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
