package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteReleaseParams creates a new DeleteReleaseParams object
// with the default values initialized.
func NewDeleteReleaseParams() DeleteReleaseParams {
	var ()
	return DeleteReleaseParams{}
}

// DeleteReleaseParams contains all the bound params for the delete release operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteRelease
type DeleteReleaseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	ReleaseName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteReleaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rReleaseName, rhkReleaseName, _ := route.Params.GetOK("releaseName")
	if err := o.bindReleaseName(rReleaseName, rhkReleaseName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteReleaseParams) bindReleaseName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ReleaseName = raw

	return nil
}
