package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubernetes-helm/monocular/src/api/swagger/models"
)

/*GetReleaseOK release information

swagger:response getReleaseOK
*/
type GetReleaseOK struct {

	// In: body
	Payload *models.ResourceData `json:"body,omitempty"`
}

// NewGetReleaseOK creates GetReleaseOK with default headers values
func NewGetReleaseOK() *GetReleaseOK {
	return &GetReleaseOK{}
}

// WithPayload adds the payload to the get release o k response
func (o *GetReleaseOK) WithPayload(payload *models.ResourceData) *GetReleaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get release o k response
func (o *GetReleaseOK) SetPayload(payload *models.ResourceData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReleaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetReleaseDefault unexpected error

swagger:response getReleaseDefault
*/
type GetReleaseDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReleaseDefault creates GetReleaseDefault with default headers values
func NewGetReleaseDefault(code int) *GetReleaseDefault {
	if code <= 0 {
		code = 500
	}

	return &GetReleaseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get release default response
func (o *GetReleaseDefault) WithStatusCode(code int) *GetReleaseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get release default response
func (o *GetReleaseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get release default response
func (o *GetReleaseDefault) WithPayload(payload *models.Error) *GetReleaseDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get release default response
func (o *GetReleaseDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReleaseDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
