package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllReleasesHandlerFunc turns a function with the right signature into a get all releases handler
type GetAllReleasesHandlerFunc func(GetAllReleasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllReleasesHandlerFunc) Handle(params GetAllReleasesParams) middleware.Responder {
	return fn(params)
}

// GetAllReleasesHandler interface for that can handle valid get all releases params
type GetAllReleasesHandler interface {
	Handle(GetAllReleasesParams) middleware.Responder
}

// NewGetAllReleases creates a new http.Handler for the get all releases operation
func NewGetAllReleases(ctx *middleware.Context, handler GetAllReleasesHandler) *GetAllReleases {
	return &GetAllReleases{Context: ctx, Handler: handler}
}

/*GetAllReleases swagger:route GET /v1/releases releases getAllReleases

get all Helm releases

*/
type GetAllReleases struct {
	Context *middleware.Context
	Handler GetAllReleasesHandler
}

func (o *GetAllReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetAllReleasesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
