apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-fdbdoclayer
  labels:
    app: {{ template "fullname" . }}-fdbdoclayer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.fdbdoclayer.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbdoclayer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fdbdoclayer
        release: {{ .Release.Name }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: fdbdoclayer
        image: {{ template "fdb.image" .Values.fdbdoclayer.image }}
        env:
        - name: FDB_COORDINATOR
          value: {{ template "fullname" . }}-fdbserver
        - name: CLUSTER_ID
          value: chartdb:erlklkg
        ports:
        - containerPort: {{ .Values.fdbdoclayer.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.fdbdoclayer.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: {{ .Values.fdbdoclayer.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 10