# Default values for monocular.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api:
  replicaCount: 2
  image:
    repository: gcr.io/helm-ui/monocular-api
    tag: latest
    pullPolicy: Always
  service:
    name: monocular-api
    type: NodePort
    externalPort: 80
    internalPort: 8081
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
ui:
  replicaCount: 2
  image:
    repository: gcr.io/helm-ui/monocular-ui
    tag: latest
    pullPolicy: Always
  service:
    name: monocular-ui
    type: NodePort
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
