swagger: "2.0"
info:
  title: Monocular
  version: 0.0.1
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
paths:
  /healthz:
    get:
      operationId: healthz
      summary: "health check"
      responses:
        200:
          description: healthy
        default:
          description: unexpected error
  /v1/charts/{repo}/{chartName}:
    get:
      operationId: getChart
      summary: "get chart by repo/name"
      parameters:
        - name: repo
          in: path
          type: string
          required: true
        - name: chartName
          in: path
          type: string
          required: true
      responses:
        200:
          description: chart response
          schema:
            $ref: "#/definitions/resourceData"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
  /v1/charts/{repo}/{chartName}/versions:
    get:
      operationId: getChartVersions
      summary: "get all chart versions by repo/name"
      parameters:
        - name: repo
          in: path
          type: string
          required: true
        - name: chartName
          in: path
          type: string
          required: true
      responses:
        200:
          description: chart response
          schema:
            $ref: "#/definitions/resourceData"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
  /v1/charts/{repo}/{chartName}/versions/{version}:
    get:
      operationId: getChartVersion
      summary: "get all chart versions by repo/name"
      parameters:
        - name: repo
          in: path
          type: string
          required: true
        - name: chartName
          in: path
          type: string
          required: true
        - name: version
          in: path
          type: string
          required: true
      responses:
        200:
          description: charts response
          schema:
            $ref: "#/definitions/resourceArrayData"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
  /v1/charts:
    get:
      operationId: getAllCharts
      summary: "get all charts from all repos"
      responses:
        200:
          description: charts response
          schema:
            $ref: "#/definitions/resourceArrayData"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
  /v1/charts/{repo}:
    get:
      operationId: getChartsInRepo
      summary: "get all charts by repo"
      parameters:
        - name: repo
          in: path
          type: string
          required: true
      responses:
        200:
          description: charts by repo response
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/resource"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
definitions:
  resource:
    type: object
    required:
      - type
      - id
      - attributes
    properties:
      type:
        type: string
        minLength: 1
      id:
        type: string
        minLength: 1
      links:
        type: object
      attributes:
        type: object
      relationships:
        type: object
  resourceData:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/resource"
  resourceArrayData:
    type: object
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/resource"
  maintainer:
    type: object
    required:
      - email
      - name
    properties:
      email:
        type: string
        minLength: 1
      name:
        type: string
        minLength: 1
  chartVersion:
    type: object
    required:
      - name
      - created
      - digest
      - description
      - home
      - maintainers
      - sources
      - urls
      - version
    properties:
      name:
        type: string
        minLength: 1
      created:
        type: string
        minLength: 1
      digest:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      icon:
        type: string
        minLength: 1
      keywords:
        type: array
        items:
          type: string
      maintainers:
        type: array
        items:
          $ref: "#/definitions/maintainer"
      version:
        type: string
        minLength: 1
      home:
        type: string
        minLength: 1
      sources:
        type: array
        items:
          type: string
      urls:
        type: array
        items:
          type: string
  chartResourceLinks:
    type: object
    required:
      - canonical
    properties:
      canonical:
        type: string
        minLength: 1
  chartResourceAttributes:
    type: object
    required:
      - name
      - description
      - repo
      - home
      - sources
      - maintainers
    properties:
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      repo:
        type: string
        minLenth: 1
      home:
        type: string
        minLength: 1
      sources:
        type: array
        items:
          type: string
      maintainers:
        type: array
        items:
          $ref: "#/definitions/maintainer"
      keywords:
        type: array
        items:
          type: string
      icon:
        type: string
        minLenth: 1
  chartVersionResourceAttributes:
    type: object
    required:
      - name
      - description
      - created
      - digest
      - repo
      - home
      - sources
      - urls
      - maintainers
      - version
    properties:
      name:
        type: string
        minLength: 1
      version:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      created:
        type: string
        minLength: 1
      digest:
        type: string
        minLength: 1
      repo:
        type: string
        minLenth: 1
      home:
        type: string
        minLength: 1
      sources:
        type: array
        items:
          type: string
      urls:
        type: array
        items:
          type: string
      maintainers:
        type: array
        items:
          $ref: "#/definitions/maintainer"
      keywords:
        type: array
        items:
          type: string
      icon:
        type: string
        minLenth: 1
  chartVersionLatestResourceAttributes:
    type: object
    required:
      - version
      - created
      - digest
      - urls
    properties:
      version:
        type: string
        minLength: 1
      created:
        type: string
        minLength: 1
      digest:
        type: string
        minLength: 1
      urls:
        type: array
        items:
          type: string
  chartLatestLinks:
    type: object
    required:
      - related
    properties:
      related:
        type: string
        minLength: 1
  chartVersionRelationshipAttributes:
    type: object
    required:
      - links
      - data
    properties:
      links:
        $ref: "#/definitions/chartLatestLinks"
      data:
        $ref: "#/definitions/chartVersionLatestResourceAttributes"
  chartLatestRelationships:
    type: object
    required:
      - chartVersionLatest
    properties:
      chartVersionLatest:
        $ref: "#/definitions/chartVersionRelationshipAttributes"
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
