package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ResourceArrayData resource array data

swagger:model resourceArrayData
*/
type ResourceArrayData struct {

	/* data

	Required: true
	*/
	Data []*Resource `json:"data"`
}

// Validate validates this resource array data
func (m *ResourceArrayData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceArrayData) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	for i := 0; i < len(m.Data); i++ {

		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {

			if err := m.Data[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
