package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/kubernetes-helm/monocular/src/api/swagger/models"
)

// NewCreateRepoParams creates a new CreateRepoParams object
// with the default values initialized.
func NewCreateRepoParams() CreateRepoParams {
	var ()
	return CreateRepoParams{}
}

// CreateRepoParams contains all the bound params for the create repo operation
// typically these are obtained from a http.Request
//
// swagger:parameters createRepo
type CreateRepoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Repository information
	  In: body
	*/
	Data *models.Repo
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateRepoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Repo
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("data", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Data = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
