package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRepoParams creates a new DeleteRepoParams object
// with the default values initialized.
func NewDeleteRepoParams() DeleteRepoParams {
	var ()
	return DeleteRepoParams{}
}

// DeleteRepoParams contains all the bound params for the delete repo operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteRepo
type DeleteRepoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	RepoName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteRepoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rRepoName, rhkRepoName, _ := route.Params.GetOK("repoName")
	if err := o.bindRepoName(rRepoName, rhkRepoName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRepoParams) bindRepoName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.RepoName = raw

	return nil
}
