package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubernetes-helm/monocular/src/api/swagger/models"
)

/*GetRepoOK repo information

swagger:response getRepoOK
*/
type GetRepoOK struct {

	// In: body
	Payload *models.ResourceData `json:"body,omitempty"`
}

// NewGetRepoOK creates GetRepoOK with default headers values
func NewGetRepoOK() *GetRepoOK {
	return &GetRepoOK{}
}

// WithPayload adds the payload to the get repo o k response
func (o *GetRepoOK) WithPayload(payload *models.ResourceData) *GetRepoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repo o k response
func (o *GetRepoOK) SetPayload(payload *models.ResourceData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRepoDefault unexpected error

swagger:response getRepoDefault
*/
type GetRepoDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRepoDefault creates GetRepoDefault with default headers values
func NewGetRepoDefault(code int) *GetRepoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRepoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get repo default response
func (o *GetRepoDefault) WithStatusCode(code int) *GetRepoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get repo default response
func (o *GetRepoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get repo default response
func (o *GetRepoDefault) WithPayload(payload *models.Error) *GetRepoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repo default response
func (o *GetRepoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
