package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepoHandlerFunc turns a function with the right signature into a get repo handler
type GetRepoHandlerFunc func(GetRepoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepoHandlerFunc) Handle(params GetRepoParams) middleware.Responder {
	return fn(params)
}

// GetRepoHandler interface for that can handle valid get repo params
type GetRepoHandler interface {
	Handle(GetRepoParams) middleware.Responder
}

// NewGetRepo creates a new http.Handler for the get repo operation
func NewGetRepo(ctx *middleware.Context, handler GetRepoHandler) *GetRepo {
	return &GetRepo{Context: ctx, Handler: handler}
}

/*GetRepo swagger:route GET /v1/repos/{repoName} repositories getRepo

get a repository enabled in the backend

*/
type GetRepo struct {
	Context *middleware.Context
	Handler GetRepoHandler
}

func (o *GetRepo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetRepoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
