package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ChartAttributes chart attributes

swagger:model chartAttributes
*/
type ChartAttributes struct {

	/* home

	Required: true
	Min Length: 1
	*/
	Home string `json:"home"`

	/* name

	Required: true
	Min Length: 1
	*/
	Name string `json:"name"`
}

// Validate validates this chart attributes
func (m *ChartAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHome(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartAttributes) validateHome(formats strfmt.Registry) error {

	if err := validate.RequiredString("home", "body", string(m.Home)); err != nil {
		return err
	}

	if err := validate.MinLength("home", "body", string(m.Home), 1); err != nil {
		return err
	}

	return nil
}

func (m *ChartAttributes) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(m.Name), 1); err != nil {
		return err
	}

	return nil
}
