package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/helm/monocular/src/api/pkg/swagger/models"
)

// GetChartHandlerFunc turns a function with the right signature into a get chart handler
type GetChartHandlerFunc func(GetChartParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChartHandlerFunc) Handle(params GetChartParams) middleware.Responder {
	return fn(params)
}

// GetChartHandler interface for that can handle valid get chart params
type GetChartHandler interface {
	Handle(GetChartParams) middleware.Responder
}

// NewGetChart creates a new http.Handler for the get chart operation
func NewGetChart(ctx *middleware.Context, handler GetChartHandler) *GetChart {
	return &GetChart{Context: ctx, Handler: handler}
}

/*GetChart swagger:route GET /v1/charts/{repo}/{chartName} getChart

get chart by repo/name

*/
type GetChart struct {
	Context *middleware.Context
	Handler GetChartHandler
}

func (o *GetChart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetChartParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

/*GetChartOKBodyBody get chart o k body body

swagger:model GetChartOKBodyBody
*/
type GetChartOKBodyBody struct {

	/* data

	Required: true
	*/
	Data *models.Chart `json:"data"`
}

// Validate validates this get chart o k body body
func (o *GetChartOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetChartOKBodyBody) validateData(formats strfmt.Registry) error {

	if o.Data != nil {

		if err := o.Data.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
