package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/helm/monocular/src/api/pkg/swagger/models"
)

// GetAllChartsHandlerFunc turns a function with the right signature into a get all charts handler
type GetAllChartsHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllChartsHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// GetAllChartsHandler interface for that can handle valid get all charts params
type GetAllChartsHandler interface {
	Handle() middleware.Responder
}

// NewGetAllCharts creates a new http.Handler for the get all charts operation
func NewGetAllCharts(ctx *middleware.Context, handler GetAllChartsHandler) *GetAllCharts {
	return &GetAllCharts{Context: ctx, Handler: handler}
}

/*GetAllCharts swagger:route GET /v1/charts getAllCharts

get all charts from all repos

*/
type GetAllCharts struct {
	Context *middleware.Context
	Handler GetAllChartsHandler
}

func (o *GetAllCharts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

/*GetAllChartsOKBodyBody get all charts o k body body

swagger:model GetAllChartsOKBodyBody
*/
type GetAllChartsOKBodyBody struct {

	/* data

	Required: true
	*/
	Data []*models.Resource `json:"data"`
}

// Validate validates this get all charts o k body body
func (o *GetAllChartsOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllChartsOKBodyBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getAllChartsOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if err := o.Data[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
