package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChartVersionHandlerFunc turns a function with the right signature into a get chart version handler
type GetChartVersionHandlerFunc func(GetChartVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChartVersionHandlerFunc) Handle(params GetChartVersionParams) middleware.Responder {
	return fn(params)
}

// GetChartVersionHandler interface for that can handle valid get chart version params
type GetChartVersionHandler interface {
	Handle(GetChartVersionParams) middleware.Responder
}

// NewGetChartVersion creates a new http.Handler for the get chart version operation
func NewGetChartVersion(ctx *middleware.Context, handler GetChartVersionHandler) *GetChartVersion {
	return &GetChartVersion{Context: ctx, Handler: handler}
}

/*GetChartVersion swagger:route GET /v1/charts/{repo}/{chartName}/versions/{version} charts getChartVersion

get specific chart version by repo/name

*/
type GetChartVersion struct {
	Context *middleware.Context
	Handler GetChartVersionHandler
}

func (o *GetChartVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetChartVersionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
