package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubernetes-helm/monocular/src/api/swagger/models"
)

/*GetAllChartsOK charts response

swagger:response getAllChartsOK
*/
type GetAllChartsOK struct {

	// In: body
	Payload *models.ResourceArrayData `json:"body,omitempty"`
}

// NewGetAllChartsOK creates GetAllChartsOK with default headers values
func NewGetAllChartsOK() *GetAllChartsOK {
	return &GetAllChartsOK{}
}

// WithPayload adds the payload to the get all charts o k response
func (o *GetAllChartsOK) WithPayload(payload *models.ResourceArrayData) *GetAllChartsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all charts o k response
func (o *GetAllChartsOK) SetPayload(payload *models.ResourceArrayData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChartsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAllChartsDefault unexpected error

swagger:response getAllChartsDefault
*/
type GetAllChartsDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChartsDefault creates GetAllChartsDefault with default headers values
func NewGetAllChartsDefault(code int) *GetAllChartsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAllChartsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get all charts default response
func (o *GetAllChartsDefault) WithStatusCode(code int) *GetAllChartsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get all charts default response
func (o *GetAllChartsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get all charts default response
func (o *GetAllChartsDefault) WithPayload(payload *models.Error) *GetAllChartsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all charts default response
func (o *GetAllChartsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChartsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
