package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAllChartsParams creates a new GetAllChartsParams object
// with the default values initialized.
func NewGetAllChartsParams() GetAllChartsParams {
	var ()
	return GetAllChartsParams{}
}

// GetAllChartsParams contains all the bound params for the get all charts operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllCharts
type GetAllChartsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetAllChartsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
